# Generated by Django 3.0b1 on 2019-10-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=2, unique=True)),
                ('iso_639_2T', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_639_2B', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_639_3', models.CharField(blank=True, max_length=3)),
                ('family', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['iso_639_1'],
            },
        ),
        migrations.CreateModel(
            name='TranslatableFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name field', max_length=250, verbose_name='Field name')),
                ('title', models.CharField(help_text="Name user's field", max_length=250, verbose_name='User field name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Translatable field',
                'verbose_name_plural': 'Translatable fields',
                'ordering': ('name',),
                'unique_together': {('title', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField(help_text='Value field', verbose_name='Value')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tof.TranslatableFields')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tof.Language')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ('sort',),
                'unique_together': {('content_type', 'object_id', 'field', 'lang')},
            },
        ),
    ]
