# Generated by Django 3.0b1 on 2019-11-18 10:00
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'languages_data.json.gz')


def del_fixture(apps, schema_editor):
    language = apps.get_model('tof', 'Language')
    language.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tof', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=del_fixture),
    ]
