# Generated by Django 3.0b1 on 2019-10-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tof', '0002_auto_20191029_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatablefields',
            options={'ordering': ('content_type', 'name'), 'verbose_name': 'Translatable field', 'verbose_name_plural': 'Translatable fields'},
        ),
        migrations.AlterUniqueTogether(
            name='translatablefields',
            unique_together={('content_type', 'name')},
        ),
    ]
