# Generated by Django 3.0rc1 on 2019-11-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tof', '0002_auto_20191118_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatablefield',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, app_label='tof'), on_delete=django.db.models.deletion.CASCADE, related_name='translatablefields', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, app_label='tof'), on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tof.TranslatableField'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='lang',
            field=models.ForeignKey(limit_choices_to=models.Q(is_active=True), on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tof.Language'),
        ),
    ]
