# Generated by Django 3.0b1 on 2019-11-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tof', '0003_auto_20191030_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translations',
            options={'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.RemoveField(
            model_name='translations',
            name='sort',
        ),
    ]
