# Generated by Django 3.0b1 on 2019-10-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort')),
                ('temperature_from', models.FloatField(blank=True, help_text='in ° C', null=True, verbose_name='Temperature_from')),
                ('temperature_to', models.FloatField(blank=True, help_text='in ° C', null=True, verbose_name='Temperature_to')),
            ],
            options={
                'verbose_name': 'wine',
                'verbose_name_plural': 'wine-plural',
                'ordering': ('title',),
            },
        ),
    ]
