# Generated by Django 3.0b1 on 2019-11-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ('sort',), 'verbose_name': 'wine', 'verbose_name_plural': 'wine-plural'},
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Year')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vintages', to='main.Wine')),
            ],
        ),
    ]
