# Generated by Django 3.0rc1 on 2019-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191119_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
